config/routes.rb
LandingPage::Application.routes.draw do
resources :items
resources :offers
resources :preorders
resources :faqs
resources :features
resources :reviews
resources :subscribers

root 'pages#home'

match '/admin_panel',  to: 'pages#admin_panel', via: 'get', as: :admin_panel
match 'item/change_show', to: 'items#show_item', via: 'put', as: :show_item
match 'offer/change_position', to: 'offers#offer_position', via: 'put', as: :offer_position
match 'items/create_preorder', to: 'items#preorder_create', via: 'post', as: :preorder_create
match 'preorder_update', to: 'items#preorder_update', via: 'put', as: :preorder_update
match 'faq/change_show', to: 'faqs#show_faq', via: 'put', as: :show_faq
match 'review/change_show', to: 'reviews#show_review', via: 'put', as: :show_review
match 'subscribe', to: 'subscribers#subscribe', via: 'get', as: :subscribe
match 'item/new_order', to: 'items#order_new', via: 'get', as: :order_new
match 'item/send_order', to: 'items#order_create', via: 'get', as: :order_create
match 'admin/signin', to: 'pages#admin_signin', via: 'get', as: :admin_signin
match 'admin_session_create', to: 'pages#admin_session_create', via: 'post', as: :admin_session
match 'admin_session_destroy', to: 'pages#admin_session_destroy', via: 'get', as: :admin_session_destroy
match 'feedback', to: 'pages#feedback', via: 'get', as: :feedback
match 'update_options', to: 'pages#update_options', via: 'put', as: :update_options
match 'update_password', to: 'pages#update_password', via: 'put', as: :update_password
match 'show_picture', to: 'pages#show_picture', via: 'get', as: :show_picture
match 'subscriber/destroy/:id', to: 'subscribers#unsubscribe',via: 'get', as: :unsubscribe 
match 'offer/new_order', to: 'offers#order_new', via: 'get', as: :offer_order_new
match 'offer/send_order', to: 'offers#order_create', via: 'get', as: :offer_order_create

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  validates :question,  presence: true
  validates :answer,  presence: true
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
	before_action :admin_user, only: [:create,:show_faq,:edit,:update,:destroy]
	include ApplicationHelper
	
	def create
    @faq = Faq.new(question: params[:question], answer: params[:answer])
    @faqs = Faq.all
    @faq.save
    respond_to do |format|
    	format.js
    end
  end

  def show_faq
  	@faq = Faq.find(params[:id])
    @faqs = Faq.all
    @faq.update_attributes(show: to_boolean(params[:show])) if Faq.where(show: true).count < 6 and to_boolean(params[:show]) or to_boolean(params[:show]) == false
    respond_to do |format|
    	format.js
    end
  end
  
  def edit
    @faq = Faq.find(params[:id])
    respond_to do |format|
    	format.js
    end
  end

  def update
    @faq = Faq.find(params[:id])
    @faqs = Faq.all
    @faq.update_attributes(answer: params[:answer], question: params[:question])
    respond_to do |format|
    	format.js
    end
  end

  def destroy
    @faqs = Faq.all
    @faq = Faq.find(params[:id])
    @faq.destroy
    respond_to do |format|
    	format.js
    end
  end

  private

    def admin_user
      unless is_admin?
        raise ActionController::RoutingError.new('Not Found')
      end
    end

end

app/views/faqs/_admin_faq.html.slim
button.btn.btn-default.btn-sm data-target="#FaqCreateModal" data-toggle="modal" 
  | Добавить      
- unless @faqs.nil?  
  table.table
          thead
            tr
              th #
              th Вопрос
              th Ответ 
              th Отображение 
              th  
          tbody
           - @count = @faqs.where(show: true).count
           - @faqs.each do |c|

            tr 
             td 
              = c.id
             td 
              = c.question
             td
              = c.answer
             td
              - if c.show == false
                - if @count < 6
                  = link_to show_faq_path(id: c.id, show: true), method: :put, remote: true do
                    = check_box_tag c.show, nil,false
                -else
                  = link_to show_faq_path(id: c.id, show: true), method: :put, remote: true do
                    = check_box_tag c.show, nil,false, disabled: true
              - else
                = link_to show_faq_path(id: c.id, show: false), method: :put,remote: true do
                  = check_box_tag c.show, nil,true
             td  
              = link_to edit_faq_path(c),remote: true do 
                i.fa.fa-pencil.fa-lg
              |  
              = link_to faq_path(c),method: :delete,remote: true do
                i.fa.fa-times.fa-lg               
                  

#FaqCreateModal.modal.fade aria-hidden="true" aria-labelledby="FaqCreateModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        h4#FaqCreateModalLabel.modal-title Новый товар
      - @i = 0
      = form_tag faqs_path, method: :post ,remote: true do 
        = hidden_field_tag :authenticity_token, form_authenticity_token  
        .modal-body
          .form-group
            = label_tag :question, "Вопрос" , class: "control-label"
            = text_field_tag :question ,nil, class: "form-control"
          .form-group
            = label_tag :answer, "Ответ" , class: "control-label"
            = text_area_tag :answer,nil, class: "form-control"

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
          = submit_tag "Добавить", class: "btn btn-primary pull-left"
#FaqEdit

app/views/faqs/_edit_modal.html.slim
#FaqEditModal.modal.fade aria-hidden="true" aria-labelledby="FaqEditModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        center  
          h4#FaqEditModalLabel.modal-title Редактировать вопрос
      - @count = 0
      = form_tag faq_path(@faq), method: :put,remote: true do   
        .modal-body
         .form-group
            = label_tag :question, "Вопрос" , class: "control-label"
            = text_field_tag :question ,@faq.question, class: "form-control"
         .form-group
            = label_tag :answer, "Ответ" , class: "control-label"
            = text_area_tag :answer,@faq.answer, class: "form-control"

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
          = submit_tag "Применить", class:  "button btn btn-primary pull-left"  

app/views/faqs/create.js.erb
$('#FaqCreateModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#faq-tab').html("<%= escape_javascript(render partial: 'faqs/admin_faq', locals: {:@faqs => @faqs}) %>");

app/views/faqs/destroy.js.erb
$('#faq-tab').html("<%= escape_javascript(render partial: 'faqs/admin_faq', locals: {:@faqs => @faqs}) %>");

app/views/faqs/edit.js.erb
$('#FaqEdit').html("<%= escape_javascript(render partial: 'faqs/edit_modal', locals: {:@faq => @faq}) %>");
$('#FaqEditModal').modal('show');

app/views/faqs/show_faq.js.erb
$('#faq-tab').html("<%= escape_javascript(render partial: 'faqs/admin_faq', locals: {:@faqs => @faqs}) %>");

app/views/faqs/update.js.erb
$('#FaqEditModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#faq-tab').html("<%= escape_javascript(render partial: 'faqs/admin_faq', locals: {:@faqs => @faqs}) %>");