config/routes.rb
LandingPage::Application.routes.draw do
resources :items
resources :offers
resources :preorders
resources :faqs
resources :features
resources :reviews
resources :subscribers

root 'pages#home'

match '/admin_panel',  to: 'pages#admin_panel', via: 'get', as: :admin_panel
match 'item/change_show', to: 'items#show_item', via: 'put', as: :show_item
match 'offer/change_position', to: 'offers#offer_position', via: 'put', as: :offer_position
match 'items/create_preorder', to: 'items#preorder_create', via: 'post', as: :preorder_create
match 'preorder_update', to: 'items#preorder_update', via: 'put', as: :preorder_update
match 'faq/change_show', to: 'faqs#show_faq', via: 'put', as: :show_faq
match 'review/change_show', to: 'reviews#show_review', via: 'put', as: :show_review
match 'subscribe', to: 'subscribers#subscribe', via: 'get', as: :subscribe
match 'item/new_order', to: 'items#order_new', via: 'get', as: :order_new
match 'item/send_order', to: 'items#order_create', via: 'get', as: :order_create
match 'admin/signin', to: 'pages#admin_signin', via: 'get', as: :admin_signin
match 'admin_session_create', to: 'pages#admin_session_create', via: 'post', as: :admin_session
match 'admin_session_destroy', to: 'pages#admin_session_destroy', via: 'get', as: :admin_session_destroy
match 'feedback', to: 'pages#feedback', via: 'get', as: :feedback
match 'update_options', to: 'pages#update_options', via: 'put', as: :update_options
match 'update_password', to: 'pages#update_password', via: 'put', as: :update_password
match 'show_picture', to: 'pages#show_picture', via: 'get', as: :show_picture
match 'subscriber/destroy/:id', to: 'subscribers#unsubscribe',via: 'get', as: :unsubscribe 
match 'offer/new_order', to: 'offers#order_new', via: 'get', as: :offer_order_new
match 'offer/send_order', to: 'offers#order_create', via: 'get', as: :offer_order_create

end

app/views/pages/_admin_options.html.slim
= form_tag update_password_path,method: :put, remote: true do 
	table.table
		tbody
			tr style = "background-color: #eeeeee;"
				td
					h4 Сменить пароль
				td
				td 
			tr
				td
					.form-group
						= password_field_tag :password,nil, class: "form-control",placeholder: "Пароль"
				td 
					.form-group
						= password_field_tag :password_confirmation,nil, class: "form-control",placeholder: "Подтверждение"
				td
					.form-group
						= submit_tag 'Применить', class: "btn btn-default", disable_with: 'Применить'
= form_tag update_options_path,method: :put, remote: true do	
	table.table
		tbody
				tr style = "background-color: #eeeeee;"
					td 
						h4  Контакты
					td
					td
				tr
					td
						h4 Адрес
					td
						= text_field_tag :adress,@adress,class: "form-control"
					td
				tr
					td
						h4 Основной телефон
					td
						= text_field_tag :phone,@phone,class: "form-control"
					td
				tr
					td
						h4 Телефон 2
					td
						= text_field_tag :phone2,@phone2,class: "form-control"
					td
				tr
					td
						h4 Телефон 3
					td
						= text_field_tag :phone3,@phone3,class: "form-control"
					td
				tr
					td
						h4 E-mail
					td
						= text_field_tag :email,@email,class: "form-control"
					td
				tr
					td
						h4 Как нас найти?
					td
						= text_area_tag :info,@info,class: "form-control"
					td
				tr
					td
						h4 О нас
					td
						= text_area_tag :about,@about,class: "form-control"
					td  
				tr
					td
						h4 Свяжитесь с нами
					td
						= text_area_tag :contact,@contact,class: "form-control"
					td         
				tr
					td
						
					td
						= submit_tag 'Применить', class: "btn btn-default", disable_with: 'Применить'
					td

app/views/pages/_feedback.html.slim
= form_tag feedback_path,method: :get, remote: true do 
	.form-group
		= text_field_tag :name, nil, class: "form-control", placeholder: "Ваше имя"
	.form-group
		= text_field_tag :email, nil, class: "form-control", placeholder: "Ваш E-mail"
	.form-group
		= text_field_tag :phone, nil, class: "form-control", placeholder: "Ваш телефон"
	.form-group
		= text_area_tag :text, nil, class: "form-control", placeholder: "Сообщение"
	.form-group
		= submit_tag 'Отправить', class: "btn btn-default", disable_with: 'Отправить'

app/views/pages/_picture_modal.html.slim
#PictureModal.modal.fade aria-hidden="true" aria-labelledby="PictureModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        center  
      .modal-body
        = image_tag @image_url

app/views/pages/admin_panel.html.slim
ul.nav.nav-tabs role="tablist" 
  li
    = link_to "Перейти на сайт", root_path
  li.active
    a data-toggle="tab" href="#items-tab" role="tab"  Товары 
  li
    a data-toggle="tab" href="#offers-tab" role="tab"  Акции
  li
    a data-toggle="tab" href="#preorders-tab" role="tab"  Предзаказ
  li
    a data-toggle="tab" href="#faq-tab" role="tab"  Вопросы
  li 
    a data-toggle="tab" href="#subscribers-tab" role="tab"  Подписчики
  li
    a data-toggle="tab" href="#reviews-tab" role="tab"  Отзывы
  li
    a data-toggle="tab" href="#options-tab" role="tab"  Настройки
  li
    = link_to "Выйти", admin_session_destroy_path
.tab-content
  #items-tab.tab-pane.active
   = render 'items/admin_items', locals: {:@items => @items} 
  #offers-tab.tab-pane
   = render 'offers/admin_offers', locals: {:@offers => @offers} 
  #preorders-tab.tab-pane 
   = render 'items/admin_preorder', locals: {:@preorder => @preorder}
  #faq-tab.tab-pane 
   = render 'faqs/admin_faq', locals: {:@faqs => @faqs}
  #subscribers-tab.tab-pane
   = render 'subscribers/admin_subscribers', locals: {:@subscribers => @subscribers}
  #reviews-tab.tab-pane 
   = render 'reviews/admin_reviews', locals: {:@reviews => @reviews}
  #options-tab.tab-pane
   = render 'pages/admin_options', locals: {:@adress => @adress,:@phone => @phone,:@email => @email,:@phone2 => @phone2,:@phone3 => @phone3,:@info => @info}

app/views/pages/admin_signin.html.slim
= form_tag admin_session_path do
	= text_field_tag :password
	= submit_tag 'Войти'

app/views/pages/feedback.js.erb
$('#feedback').html("<%= escape_javascript(render partial: 'pages/feedback') %>");
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");

app/views/pages/home.html.slim
/-provide(:title, @items.first().title)
/-provide(:description, full_description(@items))

= render 'layouts/header'

/ Товары
#banner
  .banner-inner
    .container
      .row
        #banner-carousel.carousel.slide data-ride="carousel"
          ol.carousel-indicators
            - @count = 0
            - @items.each do |i|
              = content_tag :li, :class => ("active" if @count == 0;) , :"data-slide-to" => "#{@count}", :"data-target" => "#banner-carousel" do
              - @count += 1
            - @offers.each do |o|
              li data-slide-to = "#{@count}" data-target = "#banner-carousel"
              - @count += 1
            - @count = 0
          .carousel-inner
            - @items.each do |i|
              div class = "#{count_tag(@count)}"
                .row
                  .col-xs-5.text-center
                    = link_to show_picture_path(image: i.image.url(:large)),method: :get, remote: true do 
                      = image_tag i.image.url(:medium), alt: i.title, class: "img-responsive"
                  .col-xs-7
                    h2
                      = i.title
                    p 
                      = i.description
                    ul.green
                      - i.features.each do |f|
                        li
                          = f.title
                    h3.price.pull-right
                      = i.price.to_i
                      |  
                      i.fa.fa-rub
                - @count += 1
                center
                    .banner-optin
                      .row
                        .col-md-4.col-md-offset-4
                          = button_to 'Заказать', order_new_path(id: i.id), class: "btn btn-default",method: :get, remote: true
            - @offers.each do |o|
              .item
                .row
                  .col-xs-5.text-center 
                    = link_to show_picture_path(image: o.image.url(:large)),method: :get, remote: true do 
                      = image_tag o.image.url(:medium), alt: o.title, class: "img-responsive"
                  .col-xs-7
                    h2
                      = o.title
                    p
                      = o.description
                    h3
                      = o.new_price.to_i
                      |  рублей
                    h4
                      = o.old_price.to_i
                      |  рублей
                center
                    .banner-optin
                      .row
                        .col-md-4.col-md-offset-4
                          = button_to 'Заказать', offer_order_new_path(id: o.id), class: "btn btn-default",method: :get, remote: true

/Акция
#sale.section
  - unless @offer.nil?
    .row
      .col-lg-6.col-md-6
         = link_to show_picture_path(image: @offer.image.url(:large)),method: :get, remote: true do   
          = image_tag @offer.image.url(:medium), alt: @offer.title, class: "img-responsive"
      .col-lg-6.col-md-6
        h2
          = @offer.title
        p 
          = @offer.description
        ul.normal-list
          - @offer.features.each do |f|
            li
              = f.title
        .text-center
          h3
            = @offer.new_price.to_i
            |  рублей
          h4
            = @offer.old_price.to_i
            |  рублей
        center
          .offer-optin
            .row
              .col-md-4.col-md-offset-4
                = button_to 'Заказать', offer_order_new_path(id: @offer.id), class: "btn btn-default",method: :get, remote: true
    .row
      .col-md-12.center-block.count
        h2.text-center До конца акции осталось:
        ul.countdown
          li
            = distance_of_time_in_words(Time.now, @offer.end_at - 4.hours, false, :except => [:minutes, :hours,:seconds],:accumulate_on => :days).delete('days')
            span Дней
          li
            = distance_of_time_in_words(Time.now, @offer.end_at - 4.hours, false, :except => [:days, :minutes,:months,:seconds]).delete('hours')
            span Часов
          li
            = distance_of_time_in_words(Time.now, @offer.end_at - 4.hours, false, :except => [:days, :hours,:months,:seconds]).delete('minutes')
            span Минут

/Предзаказ
#preorder.section
  - unless @preorder.nil?
    .container
      .row
        .col-lg-12
          .headline
            h1
              strong Предзаказ!
              |  
              = @preorder.title
            p 
              = @preorder.description
      .row
        .col-lg-8.col-md-8
          .row
            - @preorder.features.each do |f|
              .col-lg-6.col-md-6
                .features-list
                  i.fa.fa-gears.fa-5x
                  h4 
                    = f.title
                  p 
                    = f.value
        .col-lg-4.col-md-4
          = link_to show_picture_path(image: @preorder.image.url(:large)),method: :get, remote: true do 
            = image_tag @preorder.image.url(:medium), alt: @preorder.title, class: "img-responsive"
      center
        .preorder-optin
          .row
            .col-md-4.col-md-offset-4
              = button_to 'Предзаказ', order_new_path(id: @preorder.id), class: "btn btn-default",method: :get, remote: true

/Подписка
#subscribers.section
  = render 'subscribers/new', locals: {:@new_subscriber => @new_subscriber}

/Отзывы
#reviews.section
  = render 'reviews/show', locals: {:@reviews => @reviews}

/Вопрос - ответ
- unless @faq.empty?
  #faq.section
    .container
      .row
        .col-lg-12
          .headline
            h1 Вопрос - Ответ
            p Тут Вы можете найти самые распространненые вопросы наших покупателей и ответы на них.
      .row
        .col-lg-7.col-md-7
          - @count = 0
          - @faq.each do |f|
            .panel
              .panel-heading
                h4.panel-title
                  a.panel-toggle data-parent="#accordion" data-toggle="collapse" href="#{faq_href_tag(@count)}" 
                    i.fa.fa-plus-square
                    = f.question
              .panel-collapse.collapse id="#{faq_tag(@count)}"
                .panel-body
                  p 
                    = f.answer
            - @count += 1
        .col-lg-5.col-md-5
          = image_tag "faq.jpg", alt: "Где купить дешевый смартфон или планшет?", class: "img-responsive"

= render 'layouts/footer'

= render 'layouts/upper'

#ItemOrder
#ItemPayment
#OfferPayment
#OfferOrder
#Picture

app/views/pages/show_picture.js.erb
$('#Picture').html("<%= escape_javascript(render partial: 'pages/picture_modal', locals: {:@image_url => @image_url}) %>");
$('#PictureModal').modal('show');

app/views/pages/update_options.js.erb
$('#options-tab').html("<%= escape_javascript(render partial: 'pages/admin_options', locals: {:@adress => @adress,:@phone => @phone,:@email => @email,:@phone2 => @phone2,:@phone3 => @phone3,:@info => @info}) %>");

app/views/pages/update_password.js.erb
$('#options-tab').html("<%= escape_javascript(render partial: 'pages/admin_options', locals: {:@adress => @adress,:@phone => @phone,:@email => @email,:@phone2 => @phone2,:@phone3 => @phone3,:@info => @info}) %>");