config/routes.rb
LandingPage::Application.routes.draw do
resources :items
resources :offers
resources :preorders
resources :faqs
resources :features
resources :reviews
resources :subscribers

root 'pages#home'

match '/admin_panel',  to: 'pages#admin_panel', via: 'get', as: :admin_panel
match 'item/change_show', to: 'items#show_item', via: 'put', as: :show_item
match 'offer/change_position', to: 'offers#offer_position', via: 'put', as: :offer_position
match 'items/create_preorder', to: 'items#preorder_create', via: 'post', as: :preorder_create
match 'preorder_update', to: 'items#preorder_update', via: 'put', as: :preorder_update
match 'faq/change_show', to: 'faqs#show_faq', via: 'put', as: :show_faq
match 'review/change_show', to: 'reviews#show_review', via: 'put', as: :show_review
match 'subscribe', to: 'subscribers#subscribe', via: 'get', as: :subscribe
match 'item/new_order', to: 'items#order_new', via: 'get', as: :order_new
match 'item/send_order', to: 'items#order_create', via: 'get', as: :order_create
match 'admin/signin', to: 'pages#admin_signin', via: 'get', as: :admin_signin
match 'admin_session_create', to: 'pages#admin_session_create', via: 'post', as: :admin_session
match 'admin_session_destroy', to: 'pages#admin_session_destroy', via: 'get', as: :admin_session_destroy
match 'feedback', to: 'pages#feedback', via: 'get', as: :feedback
match 'update_options', to: 'pages#update_options', via: 'put', as: :update_options
match 'update_password', to: 'pages#update_password', via: 'put', as: :update_password
match 'show_picture', to: 'pages#show_picture', via: 'get', as: :show_picture
match 'subscriber/destroy/:id', to: 'subscribers#unsubscribe',via: 'get', as: :unsubscribe 
match 'offer/new_order', to: 'offers#order_new', via: 'get', as: :offer_order_new
match 'offer/send_order', to: 'offers#order_create', via: 'get', as: :offer_order_create

end

app/models/offer.rb
class Offer < ActiveRecord::Base
 validates :title,  presence: true
 validates :description,  presence: true
 validates :end_at, presence: true
 validates :new_price, presence: true
 validates :old_price, presence: true
 validates :old_price, presence: true

 has_many :features, dependent: :destroy

 has_attached_file :image, :styles => { :large => "600x600!", :medium => "300x300!", :thumb => "100x100!" }
 validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  include ApplicationHelper
  before_action :admin_user, only: [:create,:offer_position,:edit,:update,:destroy]

  def create
    @offer = Offer.create(title: params[:title],description: params[:description], image: params[:image], old_price: params[:old_price].to_f, new_price: params[:new_price].to_f, end_at: params[:end_at])
    @offers = Offer.all
    if @offer.save
      feature_titles = params[:feature_titles]
      for i in 0..2
        if feature_titles[i.to_s].blank?
        	break
        else 
          Feature.create(offer_id: @offer.id, title: feature_titles[i.to_s])        
        end
      end
    else
      flash[:danger] = "Ошибка! Проверьте заполнены ли все поля"
    end
    respond_to do |format|
        format.js
    end
  end

  def edit
    @offer = Offer.find(params[:id])
    respond_to do |format|
    	format.js
    end
  end 

  def offer_position
    @offer = Offer.find(params[:id])
    @offers = Offer.all
    if params[:position].to_i == 1
      @offer.update_attributes(position: params[:position].to_i) if @offers.where(position: 1).count < 3
    elsif params[:position].to_i == 2
      @offer.update_attributes(position: params[:position].to_i) if @offers.where(position: 2).count < 1
    else
      @offer.update_attributes(position: params[:position].to_i)	
    end
    respond_to do |format|
    	format.js
    end
  end

  def update
    @offer = Offer.find(params[:id])
    @offers = Offer.all
    if @offer.update_attributes(title: params[:title], description: params[:description], old_price: params[:old_price], new_price: params[:new_price], end_at: params[:end_at])
    	@offer.update_attributes(image: params[:image]) unless params[:image].blank?
    	feature_titles = params[:feature_titles]
    	feature_titles.each_key do |id|
	      begin
		    	if feature = Feature.find(id)
		        feature.update_attributes(title: feature_titles[id])
		    	end
	      rescue ActiveRecord::RecordNotFound
	        unless feature_titles[id].blank?
	        	Feature.create(title: feature_titles[id], offer_id: @offer.id)
	    	  end
	      end  	
    	end
    	respond_to do |format|
      		format.js
    	end
    else
      flash[:danger] = "Ошибка! Проверьте заполнены ли все поля"
    end
    respond_to do |format|
        format.js
    end	
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    @offers = Offer.all
    respond_to do |format|
    	format.js
    end
  end

  def order_new
    @offer = Offer.find(params[:id])
    respond_to do |format|
        format.js
    end
  end

  def order_create
    @offer = Offer.find(params[:id])
    unless params[:name].blank? or params[:email].blank? or params[:phone].blank? or params[:adress].blank? or params[:city].blank? or params[:index].blank?
      Mailer.OfferOrder(params[:name],params[:email],params[:phone],params[:payment],params[:id],params[:adress],params[:index],params[:city],params[:comment]).deliver
      @payment = params[:payment]
      @deliver = 1
    else
      flash[:danger] = "Все поля должны быть заполнены"
      @deliver = 0
    end
    respond_to do |format|
        format.js
    end
  end

  private

    def admin_user
      unless is_admin?
        raise ActionController::RoutingError.new('Not Found')
      end
    end
end

app/views/offers/_admin_offers.html.slim
button.btn.btn-default.btn-sm data-target="#OfferCreateModal" data-toggle="modal"  
  | Добавить акцию        
table.table
          thead
            tr
              th #
              th Акция 
              th Слайдер
              th Отдельно
              th Изменить/удалить
          tbody
           - @count2 = @offers.where(position: 2).count
           - @count1 = @offers.where(position: 1).count
           - @offers.each do |c|

            tr 
             td 
              = c.id
             td 
              = c.title
             td 
                - if c.position != 1
                  - if @count1 < 2
                    = link_to offer_position_path(id: c.id, position: 1), method: :put, remote: true do
                      = check_box_tag c.position, ' ',false
                  -else
                    = check_box_tag c.position, ' ',false, disabled: true
                - else
                  = link_to offer_position_path(id: c.id, position: 0), method: :put,remote: true do
                    = check_box_tag c.position, ' ',true
             td    
                - if c.position != 2
                  - if @count2 < 1
                    = link_to offer_position_path(id: c.id, position: 2), method: :put, remote: true do
                      = check_box_tag c.position, ' ',false
                  -else
                    = check_box_tag c.position, ' ',false, disabled: true
                - else
                  = link_to offer_position_path(id: c.id, position: 0), method: :put,remote: true do
                    = check_box_tag c.position, ' ',true
             td  
              = link_to edit_offer_path(c),remote: true do 
                i.fa.fa-pencil.fa-lg
              |  
              = link_to offer_path(c),method: :delete,remote: true do
                i.fa.fa-times.fa-lg               
                  

#OfferCreateModal.modal.fade aria-hidden="true" aria-labelledby="OfferCreateModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        h4#OfferCreateModalLabel.modal-title Новый товар
      - @i = 0
      = form_tag offers_path, method: :post, :enctype =>"multipart/form-data" ,remote: true do 
        = hidden_field_tag :authenticity_token, form_authenticity_token  
        .modal-body
          .form-group
            = label_tag :title, "Название" , class: "control-label"
            = text_field_tag :title ," ", class: "form-control"
          .form-group
            = label_tag :description, "Описание" , class: "control-label"
            = text_area_tag :description," ", class: "form-control"
          center
            | Пункты
          .row 
           .input-group
            = while @i < 3 do
               = text_field_tag "feature_titles[#{@i}]"," ",class: "form-control"
               -@i += 1
          center
            | Цена 
          .row  
            .input-group
              .col-lg-6
                center
                  = label_tag :title, "Старая цена" , class: "control-label"
                  = text_field_tag :old_price, " ", class: "form-control"
              .col-lg-6
                center
                  = label_tag :title, "Новая цена" , class: "control-label"
                  = text_field_tag :new_price, " ", class: "form-control"
          center
            | Дата окончания
            .input_group
               = date_field_tag :end_at

          .form-group 
            center
              | Изображение
            = file_field_tag :image,class: "form-control" 

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
          = submit_tag "Добавить", class: "btn btn-primary pull-left"
#OfferEdit

app/views/offers/_edit_modal.html.slim
#OfferEditModal.modal.fade aria-hidden="true" aria-labelledby="OfferEditModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        center  
          h4#OfferEditModalLabel.modal-title Редактировать товар
      - @count = 0
      = form_tag offer_path(@offer), method: :put,:enctype =>"multipart/form-data" ,remote: true do   
        .modal-body
         .form-group
            = label_tag :title, "Название" , class: "control-label"
            = text_field_tag :title ,@offer.title, class: "form-control"
         .form-group
            = label_tag :description, "Описание" , class: "control-label"
            = text_area_tag :description,@offer.description, class: "form-control"
         center
           | Пункты
         .row 
           .input-group
             - @offer.features.each do |f|
               = text_field_tag "feature_titles[#{f.id}]",f.title,class: "form-control"
               - @count += 1
             - while @count < 3
               = text_field_tag "feature_titles[#{@count + 44000}]"," ",class: "form-control"
               - @count += 1
           center
            | Цена 
           .row  
              .input-group
                .col-lg-6
                  center
                    = label_tag :title, "Старая цена" , class: "control-label"
                    = text_field_tag :old_price, @offer.old_price, class: "form-control"
                .col-lg-6
                  center
                    = label_tag :title, "Новая цена" , class: "control-label"
                    = text_field_tag :new_price, @offer.new_price, class: "form-control"
         center
            | Дата окончания
         .input_group
               = date_field_tag :end_at,@offer.end_at, class: "form-control"
         center
           | Изображение
         center
           = image_tag @offer.image.url(:thumb)
         .form-group 
            = file_field_tag :image,value: @offer.image,class: "form-control" 

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
          = submit_tag "Применить", class:  "button btn btn-primary pull-left"  

app/views/offers/_order_modal.html.slim
#OfferOrderModal.modal.fade aria-text="true" aria-labelledby="OfferOrderModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-text="true"  &times;
          span.sr-only Close
        center  
          h4#OfferOrderModalLabel.modal-title 
            | Заказ  
            = @offer.title 
        ul.nav.nav-tabs role="tablist" 
          li.active
            a data-toggle="tab" href="#payment1-tab" role="tab"  Наложный платёж
          li
            a data-toggle="tab" href="#payment2-tab" role="tab"  Предоплата
      .modal-body
        .tab-content
          #payment1-tab.tab-pane.active  
            center  
              = form_tag offer_order_create_path(id: @offer.id), method: :get,remote: true do
                = text_field_tag :name, nil, placeholder: "Ф.И.О"
                = text_field_tag :email, nil, placeholder: "E-mail"
                = text_field_tag :phone, nil, placeholder: "Телефон"
                = text_field_tag :city, nil, placeholder: "Город"
                = text_field_tag :index, nil, placeholder: "Почтовый индекс"
                = text_field_tag :adress, nil, placeholder: "Адрес доставки"
                = text_area_tag :comment, nil, placeholder: "Комментарий"
                = hidden_field_tag :payment, "Наложный платёж"
                = submit_tag 'Наложный платёж', class: "btn btn-default", disable_with: 'Наложный платёж'
          #payment2-tab.tab-pane
            center     
              = form_tag offer_order_create_path(id: @offer.id), method: :get,remote: true do
                = text_field_tag :name, nil, placeholder: "Ф.И.О"
                = text_field_tag :email, nil, placeholder: "E-mail"
                = text_field_tag :phone, nil, placeholder: "Телефон"
                = text_field_tag :city, nil, placeholder: "Город"
                = text_field_tag :index, nil, placeholder: "Почтовый индекс"
                = text_field_tag :adress, nil, placeholder: "Адрес доставки"
                = text_area_tag :comment, nil, placeholder: "Комментарий"
                = hidden_field_tag :payment, "Предоплата"
                = submit_tag 'Предоплата', class: "btn btn-default", disable_with: 'Предоплата'

        
      .modal-footer
          .pull-left
            | Цена:  
            = @offer.new_price.to_i
            |  
            i.fa.fa-rub
          button.btn.btn-primary data-dismiss="modal" type="button"  Закрыть

app/views/offers/_payment_modal.html.slim
#OfferPaymentModal.modal.fade aria-text="true" aria-labelledby="OfferPaymentModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-text="true"  &times;
          span.sr-only Close
        center  
          h4#OfferPaymentModalLabel.modal-title Оплатить заказ
      .modal-body  
        center
          <iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/shop.xml?account=41001972522244&quickpay=shop&payment-type-choice=on&writer=seller&targets=%D0%9E%D0%BF%D0%BB%D0%B0%D1%82%D0%B0+%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0&targets-hint=&default-sum=#{@offer.new_price.to_i - (@offer.new_price.to_i/50)}&button-text=01&fio=on&mail=on&phone=on&address=on&successURL=http%3A%2F%2Froyz-techmag.ru%2F" width="450" height="198"></iframe>

        
      .modal-footer
          button.btn.btn-primary data-dismiss="modal" type="button"  Закрыть

app/views/offers/create.js.erb
<% if @offer.errors.any? %>
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% else %>
$('#OfferCreateModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#offers-tab').html("<%= escape_javascript(render partial: 'offers/admin_offers', locals: {:@offers => @offers}) %>");
<% end %>

app/views/offers/destroy.js.erb
$('#offers-tab').html("<%= escape_javascript(render partial: 'offers/admin_offers', locals: {:@offers => @offers}) %>");

app/views/offers/edit.js.erb
$('#OfferEdit').html("<%= escape_javascript(render partial: 'offers/edit_modal', locals: {:@offer => @offer}) %>");
$('#OfferEditModal').modal('show');

app/views/offers/offer_position.js.erb
$('#offers-tab').html("<%= escape_javascript(render partial: 'offers/admin_offers', locals: {:@offers => @offers}) %>");

app/views/offers/order_create.js.erb
<% if @deliver == 1 %>
	$('#OfferOrderModal').modal('hide');
	$('body').removeClass('modal-open');
	$('.modal-backdrop').remove();
	<%- if @payment == "Предоплата"%>
		$('#OfferPayment').html("<%= escape_javascript(render partial: 'offers/payment_modal', locals: {:@offer => @offer}) %>");
		$('#OfferPaymentModal').modal('show');
	<%- end%>
<% else %>
	$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% end %>

app/views/offers/order_new.js.erb
<%- unless @offer.nil? %>
$('#OfferOrder').html("<%= escape_javascript(render partial: 'offers/order_modal', locals: {:@offer => @offer}) %>");
$('#OfferOrderModal').modal('show');
<%- end %>

app/views/offers/update.js.erb
<% if @offer.errors.any? %>
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% else %>
$('#OfferEditModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#offers-tab').html("<%= escape_javascript(render partial: 'offers/admin_offers', locals: {:@offers => @offers}) %>");
<% end %>