config/routes.rb
LandingPage::Application.routes.draw do
resources :items
resources :offers
resources :preorders
resources :faqs
resources :features
resources :reviews
resources :subscribers

root 'pages#home'

match '/admin_panel',  to: 'pages#admin_panel', via: 'get', as: :admin_panel
match 'item/change_show', to: 'items#show_item', via: 'put', as: :show_item
match 'offer/change_position', to: 'offers#offer_position', via: 'put', as: :offer_position
match 'items/create_preorder', to: 'items#preorder_create', via: 'post', as: :preorder_create
match 'preorder_update', to: 'items#preorder_update', via: 'put', as: :preorder_update
match 'faq/change_show', to: 'faqs#show_faq', via: 'put', as: :show_faq
match 'review/change_show', to: 'reviews#show_review', via: 'put', as: :show_review
match 'subscribe', to: 'subscribers#subscribe', via: 'get', as: :subscribe
match 'item/new_order', to: 'items#order_new', via: 'get', as: :order_new
match 'item/send_order', to: 'items#order_create', via: 'get', as: :order_create
match 'admin/signin', to: 'pages#admin_signin', via: 'get', as: :admin_signin
match 'admin_session_create', to: 'pages#admin_session_create', via: 'post', as: :admin_session
match 'admin_session_destroy', to: 'pages#admin_session_destroy', via: 'get', as: :admin_session_destroy
match 'feedback', to: 'pages#feedback', via: 'get', as: :feedback
match 'update_options', to: 'pages#update_options', via: 'put', as: :update_options
match 'update_password', to: 'pages#update_password', via: 'put', as: :update_password
match 'show_picture', to: 'pages#show_picture', via: 'get', as: :show_picture
match 'subscriber/destroy/:id', to: 'subscribers#unsubscribe',via: 'get', as: :unsubscribe 
match 'offer/new_order', to: 'offers#order_new', via: 'get', as: :offer_order_new
match 'offer/send_order', to: 'offers#order_create', via: 'get', as: :offer_order_create

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title,  presence: true
  validates :description,  presence: true


  has_many :features, dependent: :destroy

  has_attached_file :image, :styles => { :large => "600x600!", :medium => "300x300!", :thumb => "100x100!" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :admin_user, only: [:create,:show_item,:edit,:update,:destroy,:preorder_create,:preorder_update]

  include ApplicationHelper

  def create
    @item = Item.create(title: params[:title],description: params[:description], image: params[:image], price: params[:price].to_i)
    @items = Item.all
    if @item.save
    	feature_titles = params[:feature_titles]
      for i in 0..7
        if feature_titles[i.to_s].blank?
        	break
        else 
          Feature.create(item_id: @item.id, title: feature_titles[i.to_s])        
        end
      end
    else
      flash[:danger] = "Ошибка! Проверьте заполнены ли все поля"
    end
    respond_to do |format|
        format.js
    end
  end
  
  def show_item
    @item = Item.find(params[:id])
    @items = Item.all
    priority = Item.where(show:true).count
    if Item.where(show: true).count < 3 and to_boolean(params[:show]) or to_boolean(params[:show]) == false
      @item.update_attributes(show: to_boolean(params[:show]))
      if to_boolean(params[:show]) == true
        @item.update_attributes(priority: priority + 1)
      else
      	@item.update_attributes(priority: 0)
      end
    end
    respond_to do |format|
    	format.js
    end
  end   

  def edit
    @item = Item.find(params[:id])
    respond_to do |format|
    	format.js
    end
  end 

  def update
    @item = Item.find(params[:id])
    @items = Item.all
    if @item.update_attributes(title: params[:title], description: params[:description], price: params[:price].to_i)
    	@item.update_attributes(image: params[:image]) unless params[:image].blank?
    	feature_titles = params[:feature_titles]
    	feature_titles.each_key do |id|
	      begin
		    	if feature = Feature.find(id)
		        feature.update_attributes(title: feature_titles[id])
		      end
	      rescue ActiveRecord::RecordNotFound
	        unless feature_titles[id].blank?
	        	Feature.create(title: feature_titles[id], item_id: @item.id)
	    	  end
	      end  	
      end
    else
      flash[:danger] = "Ошибка! Проверьте заполнены ли все поля"
    end
    respond_to do |format|
        format.js
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    @items = Item.all
    respond_to do |format|
      format.js
    end
  end


  def preorder_create
    @item = Item.create(title: params[:title],description: params[:description], image: params[:image], preorder: true)
    if @item.save
    	feature_titles = params[:feature_titles]
    	feature_values = params[:feature_values]
      for i in 0..3
        if feature_titles[i.to_s].blank? or feature_values[i.to_s].blank?
        	break
        else 
          Feature.create(item_id: @item.id, title: feature_titles[i.to_s], value: feature_values[i.to_s] )        
        end
      end
    else
      flash[:danger] = "Ошибка! Проверьте заполнены ли все поля"
    end
    respond_to do |format|
        format.js
    end
  end

  def preorder_update
    @item = Item.find(params[:id])
    @items = Item.all
    if @item.update_attributes(title: params[:title], description: params[:description])
    	@item.update_attributes(image: params[:image]) unless params[:image].blank?
    	feature_titles = params[:feature_titles]
    	feature_values = params[:feature_values]
    	feature_titles.each_key do |id|
	      begin
		    	if feature = Feature.find(id)
		        feature.update_attributes(title: feature_titles[id], value: feature_values[id])
		      end
	      rescue ActiveRecord::RecordNotFound
	        unless feature_titles[id].blank? or feature_values[id].blank?
	        	Feature.create(title: feature_titles[id],value: feature_values[id], item_id: @item.id)
	    	  end
	      end  	
    	end
      flash[:success] = "Предзаказ обновлён"
    else
      flash[:danger] = "Ошибка! Проверьте заполнены ли все поля"
    end
    respond_to do |format|
        format.js
    end
  end

  def order_new
  	@item = Item.find(params[:id])
    @items = Item.where(show: true)
  	respond_to do |format|
        format.js
    end
  end

  def order_create
    @item = Item.find(params[:id])
    unless params[:name].blank? or params[:email].blank? or params[:phone].blank? or params[:adress].blank? or params[:city].blank? or params[:index].blank?
      Mailer.ItemOrder(params[:name],params[:email],params[:phone],params[:payment],params[:id],params[:adress],params[:index],params[:city],params[:comment]).deliver
      @payment = params[:payment]
      @deliver = 1
    else
      flash[:danger] = "Все поля должны быть заполнены"
      @deliver = 0
    end
    respond_to do |format|
        format.js
    end
  end

  private

    def admin_user
      unless is_admin?
        raise ActionController::RoutingError.new('Not Found')
      end
    end





end

app/views/items/_admin_items.html.slim
button.btn.btn-default.btn-sm data-target="#ItemCreateModal" data-toggle="modal" 
  | Добавить товар       
table.table
          thead
            tr
              th #
              th Товар  
              th Отображение 
              th  
          tbody
           - @count = @items.where(show: true).count
           - @items.each do |c|

            tr 
             td 
              = c.id
             td 
              = c.title
              - if c.preorder?
                | (Предзаказ)
             td
              - unless c.preorder?
                - if c.show == false
                  - if @count < 3
                    = link_to show_item_path(id: c.id, show: true), method: :put, remote: true do
                      = check_box_tag c.show, ' ',false
                  -else
                    = link_to show_item_path(id: c.id, show: true), method: :put, remote: true do
                      = check_box_tag c.show, ' ',false, disabled: true
                - else
                  = link_to show_item_path(id: c.id, show: false), method: :put,remote: true do
                    = check_box_tag c.show, ' ',true
             td  
              = link_to edit_item_path(c),remote: true do 
                i.fa.fa-pencil.fa-lg
              |  
              = link_to item_path(c),method: :delete,remote: true do
                i.fa.fa-times.fa-lg               
                  

#ItemCreateModal.modal.fade aria-hidden="true" aria-labelledby="ItemCreateModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        h4#ItemCreateModalLabel.modal-title Новый товар
      - @i = 0
      = form_tag items_path, method: :post, :enctype =>"multipart/form-data" ,remote: true do 
        = hidden_field_tag :authenticity_token, form_authenticity_token  
        .modal-body
          .form-group
            = label_tag :title, "Название" , class: "control-label"
            = text_field_tag :title ,nil, class: "form-control"
          .form-group
            = label_tag :description, "Описание" , class: "control-label"
            = text_area_tag :description,nil, class: "form-control"
          form-group
            = label_tag :price, "Цена" , class: "control-label"
            = text_field_tag :price,nil, class: "form-control"
          center
            | Характеристики
          .row 
           .input-group
            = while @i < 8 do
               = text_field_tag "feature_titles[#{@i}]"," ",class: "form-control"
               - @i+=1
          .form-group 
            center
              | Изображение
            = file_field_tag :image,class: "form-control" 

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
          = submit_tag "Добавить", class: "btn btn-primary pull-left"
#ItemEdit

app/views/items/_admin_preorder.html.slim
- if @preorder.nil?
  center
    button.btn.btn-default.btn-sm data-target="#PreorderCreateModal" data-toggle="modal" Добавить предзаказ

  #PreorderCreateModal.modal.fade aria-hidden="true" aria-labelledby="PreorderCreateModalLabel" role="dialog" tabindex="-1" 
    .modal-dialog
      .modal-content
        .modal-header
          button.close data-dismiss="modal" type="button" 
            span aria-hidden="true"  &times;
            span.sr-only Close
          h4#PreorderCreateModalLabel.modal-title Новый товар
        - @i = 0
        = form_tag preorder_create_path, method: :post, :enctype =>"multipart/form-data" ,remote: true do 
          = hidden_field_tag :authenticity_token, form_authenticity_token  
          .modal-body
            .form-group
              = label_tag :title, "Название" , class: "control-label"
              = text_field_tag :title ,nil, class: "form-control"
            .form-group
              = label_tag :description, "Описание" , class: "control-label"
              = text_area_tag :description,nil, class: "form-control"
            center
              | Поля
            .row 
             .input-group
              = while @i < 4 do
                .col-md-6
                   = text_field_tag "feature_titles[#{@i}]",nil,class: "form-control"
                .col-md-6   
                   = text_field_tag "feature_values[#{@i}]",nil,class: "form-control"
                - @i+=1
            .form-group 
              center
                | Изображение
              = file_field_tag :image,class: "form-control" 

          .modal-footer
            button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
            = submit_tag "Добавить", class: "btn btn-primary pull-left" 
- else 
  center  
    = form_tag preorder_update_path(id: @preorder.id),remotipart_submitted: true ,method: :put, :enctype =>"multipart/form-data", remote: true do      
      table.table
        tbody
          tr
            td
              | Название
            td
              .form-group
                = text_field_tag :title, @preorder.title, class: "form-control"
          tr
            td
              | Описание
            td
              .form-group
                = text_area_tag :description, @preorder.description, class: "form-control"
          tr 
            td 
              | Поля
            td
              .row 
                .input-group
                  - @count = 0
                  - @preorder.features.each do |f|
                    .col-md-6
                      = text_field_tag "feature_titles[#{f.id}]",f.title,class: "form-control"
                    .col-md-6
                      = text_field_tag "feature_values[#{f.id}]",f.value,class: "form-control"
                    - @count+=1
                  - while @count < 4
                    .col-md-6
                      = text_field_tag "feature_titles[#{@count + 44000}]",nil,class: "form-control"
                    .col-md-6
                      = text_field_tag "feature_values[#{@count + 44000}]",nil,class: "form-control"
                    - @count+=1
          tr  
            td
              | Изображение
            td
              .col-md-4
                = image_tag @preorder.image.url(:thumb)
                = file_field_tag :image,value: @preorder.image,class: "form-control" 
          tr
            td
            td
              .col-md-6.col-md-offset-5   
                = submit_tag "Подтвердить", class: "btn btn-primary pull-left" 
                

app/views/items/_edit_modal.html.slim
#ItemEditModal.modal.fade aria-hidden="true" aria-labelledby="ItemEditModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        center  
          h4#ItemEditModalLabel.modal-title Редактировать товар
      - @count = 0
      = form_tag item_path(@item), method: :put,:enctype =>"multipart/form-data" ,remote: true do   
        .modal-body
         .form-group
            = label_tag :title, "Название" , class: "control-label"
            = text_field_tag :title ,@item.title, class: "form-control"
         .form-group
            = label_tag :description, "Описание" , class: "control-label"
            = text_area_tag :description,@item.description, class: "form-control"
         .form-group
            = label_tag :price, "Цена" , class: "control-label"
            = text_field_tag :price ,@item.price, class: "form-control"
         center
           | Характеристики
         .row 
           .input-group
             - @item.features.each do |f|
               = text_field_tag "feature_titles[#{f.id}]",f.title,class: "form-control"
               - @count+=1
             - while @count < 8
               = text_field_tag "feature_titles[#{@count + 44000}]"," ",class: "form-control"
               - @count += 1
         center
           | Изображение
         center
           = image_tag @item.image.url(:thumb)
         .form-group 
            = file_field_tag :image,value: @item.image,class: "form-control" 

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Закрыть
          = submit_tag "Применить", class:  "button btn btn-primary pull-left"  

app/views/items/_order_modal.html.slim
#ItemOrderModal.modal.fade aria-text="true" aria-labelledby="ItemOrderModalLabel" role="dialog" tabindex="-1" 
	.modal-dialog
		.modal-content
			.modal-header
				button.close data-dismiss="modal" type="button" 
					span aria-text="true"  &times;
					span.sr-only Close
				center  
					h4#ItemOrderModalLabel.modal-title 
						| Заказ  
						.dropdown.animated.fadeInDown.animation-delay-11
							a.dropdown-toggle data-toggle="dropdown" href="#" 
								= @item.title
							.dropdown-menu.dropdown-menu-right.dropdown-call-box.animated.fadeInUp
								- @items.each do |i|
									= link_to i.title, order_new_path(id: i.id), class: "btn btn-default",method: :get, remote: true
				ul.nav.nav-tabs role="tablist" 
					li.active
						a data-toggle="tab" href="#payment1-tab" role="tab"  Наложный платёж
					li
						a data-toggle="tab" href="#payment2-tab" role="tab"  Предоплата
			.modal-body
				.tab-content
					#payment1-tab.tab-pane.active  
						center  
							= form_tag order_create_path(id: @item.id), method: :get,remote: true do
								= text_field_tag :name, nil, placeholder: "Ф.И.О"
								= text_field_tag :email, nil, placeholder: "E-mail"
								= text_field_tag :phone, nil, placeholder: "Телефон"
								= text_field_tag :city, nil, placeholder: "Город"
								= text_field_tag :index, nil, placeholder: "Почтовый индекс"
								= text_field_tag :adress, nil, placeholder: "Адрес доставки"
								= text_area_tag :comment, nil, placeholder: "Комментарий"
								= hidden_field_tag :payment, "Наложный платёж"
								= submit_tag 'Наложный платёж', class: "btn btn-default", disable_with: 'Наложный платёж'
					#payment2-tab.tab-pane
						center     
							= form_tag order_create_path(id: @item.id), method: :get,remote: true do
								= text_field_tag :name, nil, placeholder: "Ф.И.О"
								= text_field_tag :email, nil, placeholder: "E-mail"
								= text_field_tag :phone, nil, placeholder: "Телефон"
								= text_field_tag :city, nil, placeholder: "Город"
								= text_field_tag :index, nil, placeholder: "Почтовый индекс"
								= text_field_tag :adress, nil, placeholder: "Адрес доставки"
								= text_area_tag :comment, nil, placeholder: "Комментарий"
								= hidden_field_tag :payment, "Предоплата"
								= hidden_field_tag :item, @item.id
								= submit_tag 'Предоплата', class: "btn btn-default", disable_with: 'Предоплата'

				
			.modal-footer
					.pull-left
						| Цена:  
						= @item.price.to_i
						|  
						i.fa.fa-rub
					button.btn.btn-primary data-dismiss="modal" type="button"  Закрыть

app/views/items/_payment_modal.html.slim
#ItemPaymentModal.modal.fade aria-text="true" aria-labelledby="ItemPaymentModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-text="true"  &times;
          span.sr-only Close
        center  
          h4#ItemPaymentModalLabel.modal-title Оплатить заказ
      .modal-body  
        center
          <iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/shop.xml?account=41001972522244&quickpay=shop&payment-type-choice=on&writer=seller&targets=%D0%9E%D0%BF%D0%BB%D0%B0%D1%82%D0%B0+%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0&targets-hint=&default-sum=#{@item.price.to_i - (@item.price.to_i/50)}&button-text=01&fio=on&mail=on&phone=on&address=on&successURL=http%3A%2F%2Froyz-techmag.ru%2F" width="450" height="198"></iframe>

        
      .modal-footer
          button.btn.btn-primary data-dismiss="modal" type="button"  Закрыть

app/views/items/create.js.erb
<% if @item.errors.any? %>
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% else %>
$('#ItemCreateModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#items-tab').html("<%= escape_javascript(render partial: 'items/admin_items', locals: {:@items => @items}) %>");
<% end %>

app/views/items/destroy.js.erb
$('#items-tab').html("<%= escape_javascript(render partial: 'items/admin_items', locals: {:@items => @items}) %>");

app/views/items/edit.js.erb
$('#ItemEdit').html("<%= escape_javascript(render partial: 'items/edit_modal', locals: {:@item => @item}) %>");
$('#ItemEditModal').modal('show');

app/views/items/order_create.js.erb
<% if @deliver == 1 %>
	$('#ItemOrderModal').modal('hide');
	$('body').removeClass('modal-open');
	$('.modal-backdrop').remove();
	<%- if @payment == "Предоплата"%>
		$('#ItemPayment').html("<%= escape_javascript(render partial: 'items/payment_modal', locals: {:@item => @item}) %>");
		$('#ItemPaymentModal').modal('show');
	<%- end%>
<% else %>
	$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% end %>

app/views/items/order_new.js.erb
<%- unless @item.nil? %>
$('#ItemOrderModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#ItemOrder').html("<%= escape_javascript(render partial: 'items/order_modal', locals: {:@item => @item}) %>");
$('#ItemOrderModal').modal('show');
<%- end %>

app/views/items/preorder_create.js.erb
<% if @item.errors.any? %>
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% else %>
$('#PreorderCreateModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#preorders-tab').html("<%= escape_javascript(render partial: 'items/admin_preorder', locals: {:@preorder => @item}) %>");
<% end %>

app/views/items/preorder_update.js.erb
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
$('#preorders-tab').html("<%= escape_javascript(render partial: 'items/admin_preorder', locals: {:@preorder => @item}) %>");

app/views/items/show_item.js.erb
$('#items-tab').html("<%= escape_javascript(render partial: 'items/admin_items', locals: {:@items => @items}) %>");

app/views/items/update.js.erb
<% if @item.errors.any? %>
$('#flash').html("<%= escape_javascript(render partial: 'shared/flash_messages', flash: flash) %>");
<% else %>
$('#ItemEditModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#items-tab').html("<%= escape_javascript(render partial: 'items/admin_items', locals: {:@items => @items}) %>");
<% end %>